include:
  - board: seeeduino_xiao_ble
    shield: futaba_left
    snippet: 
      - studio-rpc-usb-uart
      -  zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: seeeduino_xiao_ble
    shield: futaba_right
    snippet:
      - studio-rpc-usb-uart
      -  zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
